var w=5;
var wtitle='电脑音乐发布直播精彩回放（';
var year=2021;
var date=2;
var day=1;
var inw='精 彩 断 线<br>多 重 鼠 标<br>另 外 插 播<br>精 彩 失 误<br>不 见 不 散'
var ty=1; 
var by='笔稽菌<br>可能会发到B站（视频版）';
var la='la';
document.getElementById("a").src="/f/1.jpg";
document.getElementById("b").src ="/f/2.jpg";
document.getElementById("c").src ="/f/3.jpg";
document.getElementById("d").src ="/f/4.jpg";
document.getElementById("e").src ="/f/5.jpg";
